name: HLootchest
version: 1.2.3
api-version: "1.13"
main: org.twightlight.hlootchest.HLootChest
depend: [TwightLightCore]
softdepend: [PlaceholderAPI, packetevents, HeadDatabase, BedWars1058, BedWars2023]
author: TwightLight
load: POSTWORLD
commands:
  hlootchests:
    description: main command
    usage: /hlootchests
    aliases:
      - hlootchest
      - lootchests
      - lootchest
      - lc
      - hlc
  hlootchestsadmin:
    description: admin command
    usage: /hlootchestsadmin
    aliases:
      - hlootchestadmin
      - lootchestsadmin
      - lootchestadmin
      - lca
      - hlca
